### ISSUE TITLE
the paper's prediction  in table 3 can's find in valid.tgt.txt

### ISSUE THREAD

**Issue by lizhenping** [YuxiXie/SG-Deep-Question-Generation#10]
hi:
   i can't find the table.3's G.T's question in both valid and train dataset? anyone have the same question or i find in the wrong place?

**Comment by raaedahmed23** [comment]
did you find them?

**Comment by YuxiXie** [comment]
Hi, thanks for asking. The examples in table 3 are just to illustrate different types of errors. Due to the various lengths of text in real datapoints, we didn't choose exactly from the dataset.
