### ISSUE TITLE
unable to run get_coref_and_dep_data.py 

### ISSUE THREAD

**Issue by raaedahmed23** [YuxiXie/SG-Deep-Question-Generation#12]
Hi, I'm using allennlp 1.0.0 and allennlp-models 1.0.0. 
While running the file `get_coref_and_dep_data.py` using the command - `python preprocess/get_coref_and_dep_data.pn.json data.valid.json dp.json crf_rsltn.json`, The following error shows: 

` File "/-------/------/.local/lib/python3.8/site-packages/allennlp/common/params.py", line 237, in pop
    value = self.params.pop(key)
KeyError: 'token_embedders'`
`allennlp.common.checks.ConfigurationError: key "token_embedders" is required at location "model.text_field_embedder."`
How do you resolve this error? I have tried running the code using 2.7.0 version of allennlp and allennlp-models, but the error remains.

**Comment by lizhenping** [comment]
> Hi, I'm using allennlp 1.0.0 and allennlp-models 1.0.0. While running the file `get_coref_and_dep_data.py` using the command - `python preprocess/get_coref_and_dep_data.pn.json data.valid.json dp.json crf_rsltn.json`, The following error shows:
> 
> ` File "/-------/------/.local/lib/python3.8/site-packages/allennlp/common/params.py", line 237, in pop value = self.params.pop(key) KeyError: 'token_embedders'` `allennlp.common.checks.ConfigurationError: key "token_embedders" is required at location "model.text_field_embedder."` How do you resolve this error? I have tried running the code using 2.7.0 version of allennlp and allennlp-models, but the error remains.

i fix it see coreference_resolution：

**Comment by YuxiXie** [comment]
Hi here! Thanks for asking. The problem seems to come from the update of allennlp.
You may need to install `allennlp==0.9.0` instead with `overrides==3.1.0`.
We've also updated the paths to the predictors in `get_coref_and_dep_data.py`. 
Thanks!
