### ISSUE TITLE
if the model can run on multi-gpu card

### ISSUE THREAD

**Issue by lizhenping** [YuxiXie/SG-Deep-Question-Generation#13]
i find someplace error when run muti-card, for example, in EncoderTransformer, the variable length is a list type in EncoderTransformer  ,can't be Assign to multiple cards when run on multi-card

**Comment by lizhenping** [comment]
perhaps this code can't run on mulit-card , i check the code ,the list Storage the position of the entity is a dynamic-length list , hard to turn to tensor, so I am sure this code can't run on multi-card

**Comment by YuxiXie** [comment]
Thanks for your checking. As you pointed out, our `Dataset` class doesn't support multi-card running due to the problem of input data format.
