### ISSUE TITLE
coreference_resolution： 

### ISSUE THREAD

**Issue by lizhenping** [YuxiXie/SG-Deep-Question-Generation#15]
when process data in preprocess_raw_data.py of the coreference_resolution in coreference_resolution:
raw = {d[0]: '\t'.join(d[1]) for d in raw}
seems should be:

raw = {d: '\t'.join(raw[d]) for d in raw}

**Comment by qjncxj** [comment]
I also encounter the same problem, looking forward to the authors' answer.

**Comment by YuxiXie** [comment]
Thanks for pointing out the issue. Sorry that there exists some inconsistency in our processing codes. 
We've fixed the problem according to your advice. Thanks!
