### ISSUE TITLE
I could not find the file /datasets/json-data/train.tag.json

### ISSUE THREAD

**Issue by qjncxj** [YuxiXie/SG-Deep-Question-Generation#16]
When I run scripts/preprocess_data.sh, I get the following error:

No such file or directory: '/home/visionx/xj/SG-Deep-Question-Generation-master/datasets/json-data/train.tag.json'

I have downloaded the directory datasets/json-data that has not the file train.tag.json. Could you help me?

**Comment by YuxiXie** [comment]
Hi, the `train.tag.json` represent `train.dp.tag.json` and `train.srl.tag.json`. To reproduce our work, you may need to set it as `train.dp.tag.json`. Thanks!

**Comment by qjncxj** [comment]
Thank you very much.
