### ISSUE TITLE
The data about build-semantic-graphs

### ISSUE THREAD

**Issue by Frankszc** [YuxiXie/SG-Deep-Question-Generation#2]
Hello, thanks for your great work!
Maybe there is a bug in the code of "merge.py" about line 85 and  86,  sys.argv[2] and sys.argv[3] are in the opposite position.
And can you release the code about how to preprocess the raw data to get "crf_rsltn.json" and "dp.json" and the data of "data.json", "crf_rsltn.json" and "dp.json" ?
Thanks again!!

**Comment by YuxiXie** [comment]
Hi! Thanks for your asking. We have just updated the folder of `build-semantic-graphs` to fix the bug. You could also find the preprocessing codes in the folder of `preprocess` now.

**Comment by Frankszc** [comment]
> Hi! Thanks for your asking. We have just updated the folder of build-semantic-graphs to fix the bug. You could also find the preprocessing codes in the folder of preprocess now.

Thanks for your reply!
And I wonder that "Word embeddings are initialized with 300-dimensional pre-trained GloVe" in the  paper, but when I read the code about the encoder, I found maybe  you use the Randomly initialized embedding. 
Thanks again!!!

**Comment by YuxiXie** [comment]
> > Hi! Thanks for your asking. We have just updated the folder of build-semantic-graphs to fix the bug. You could also find the preprocessing codes in the folder of preprocess now.
> 
> Thanks for your reply!
> And I wonder that "Word embeddings are initialized with 300-dimensional pre-trained GloVe" in the paper, but when I read the code about the encoder, I found maybe you use the Randomly initialized embedding.
> Thanks again!!!

Hi! You need to define the argument of `-pre_trained_vocab`, like what we do in the [`scripts/preprocess_data.sh`](https://github.com/YuxiXie/SG-Deep-Question-Generation/blob/master/scripts/preprocess_data.sh), to define what kinds of GloVe embeddings to use. 
You could refer to the function [`get_embedding(vocab_dict, vocab)`](https://github.com/YuxiXie/SG-Deep-Question-Generation/blob/e6246edddd9c3ea2b796af4954925357a3ac53c8/src/preprocess.py#L110) in the file [`src/preprocess.py`](https://github.com/YuxiXie/SG-Deep-Question-Generation/blob/master/src/preprocess.py) for details. Here we assign embeddings to each word in the current vocabulary, _i.e._ only randomly initialize those which are not in GloVe.

```python
  def get_vector(idx):
        word = vocab.idxToLabel[idx]
        if idx in vocab.special or word not in vocab_dict:
            ##=== words not in GloVe ===##
            vector = torch.tensor([])
            vector = vector.new_full((opt.word_vec_size,), 1.0)
            vector.normal_(0, math.sqrt(6 / (1 + vector.size(0))))
        else:
            ##=== words in GloVe ===##
            vector = torch.Tensor(vocab_dict[word])
        return vector
```

**Comment by Frankszc** [comment]
> Hi! Thanks for your asking. We have just updated the folder of build-semantic-graphs to fix the bug. You could also find the preprocessing codes in the folder of preprocess now.
> 
> Thanks for your reply!
> And I wonder that "Word embeddings are initialized with 300-dimensional pre-trained GloVe" in the paper, but when I read the code about the encoder, I found maybe you use the Randomly initialized embedding.
> Thanks again!!!
> 
> Hi! You need to define the argument of -pre_trained_vocab, like what we do in the scripts/preprocess_data.sh, to define what kinds of GloVe embeddings to use.
> You could refer to the function get_embedding(vocab_dict, vocab) in the file src/preprocess.py for details. Here we assign embeddings to each word in the current vocabulary, i.e. only randomly initialize those which are not in GloVe.
>   def get_vector(idx):
>         word = vocab.idxToLabel[idx]
>         if idx in vocab.special or word not in vocab_dict:
>             ##=== words not in GloVe ===##
>             vector = torch.tensor([])
>             vector = vector.new_full((opt.word_vec_size,), 1.0)
>             vector.normal_(0, math.sqrt(6 / (1 + vector.size(0))))
>         else:
>             ##=== words in GloVe ===##
>             vector = torch.Tensor(vocab_dict[word])
>         return vector

Hello, Thanks for your reply!!
Yeah, we can get the corresponding glove embedding about the source sentence and answer which is saved in the "pre_trained_vocab" in the file src/preprocess.py, but maybe you don't use the glove embedding("pre_trained_vocab") to initialize in the class "RNNEncoder"( [https://github.com/YuxiXie/SG-Deep-Question-Generation/blob/9387c446499ca23e072c4d6a47865ae6d2ce1848/src/onqg/models/Encoders.py#L14](url) ), I found that you use the Randomly initialized embedding by nn.embedding. I mean that maybe you don't use the glove embedding in the current code.
Thanks again!!!!!

**Comment by YuxiXie** [comment]
> > Hi! Thanks for your asking. We have just updated the folder of build-semantic-graphs to fix the bug. You could also find the preprocessing codes in the folder of preprocess now.
> > Thanks for your reply!
> > And I wonder that "Word embeddings are initialized with 300-dimensional pre-trained GloVe" in the paper, but when I read the code about the encoder, I found maybe you use the Randomly initialized embedding.
> > Thanks again!!!
> > Hi! You need to define the argument of -pre_trained_vocab, like what we do in the scripts/preprocess_data.sh, to define what kinds of GloVe embeddings to use.
> > You could refer to the function get_embedding(vocab_dict, vocab) in the file src/preprocess.py for details. Here we assign embeddings to each word in the current vocabulary, i.e. only randomly initialize those which are not in GloVe.
> > def get_vector(idx):
> > word = vocab.idxToLabel[idx]
> > if idx in vocab.special or word not in vocab_dict:
> > ##=== words not in GloVe ===##
> > vector = torch.tensor([])
> > vector = vector.new_full((opt.word_vec_size,), 1.0)
> > vector.normal_(0, math.sqrt(6 / (1 + vector.size(0))))
> > else:
> > ##=== words in GloVe ===##
> > vector = torch.Tensor(vocab_dict[word])
> > return vector
> 
> Hello, Thanks for your reply!!
> Yeah, we can get the corresponding glove embedding about the source sentence and answer which is saved in the "pre_trained_vocab" in the file src/preprocess.py, but maybe you don't use the glove embedding("pre_trained_vocab") to initialize in the class "RNNEncoder"( [https://github.com/YuxiXie/SG-Deep-Question-Generation/blob/9387c446499ca23e072c4d6a47865ae6d2ce1848/src/onqg/models/Encoders.py#L14](url) ), I found that you use the Randomly initialized embedding by nn.embedding. I mean that maybe you don't use the glove embedding in the current code.
> Thanks again!!!!!

Got it. 
You could refer to the command of model initialization at https://github.com/YuxiXie/SG-Deep-Question-Generation/blob/9387c446499ca23e072c4d6a47865ae6d2ce1848/src/train.py#L95, where we call the function [`build_model(opt, device, separate=-1, checkpoint)`](https://github.com/YuxiXie/SG-Deep-Question-Generation/blob/9387c446499ca23e072c4d6a47865ae6d2ce1848/src/onqg/utils/model_builder.py#L89) in the file [`src/onqg/utils/model_builder.py`](https://github.com/YuxiXie/SG-Deep-Question-Generation/blob/master/src/onqg/utils/model_builder.py).
Then you could find in this file that we call the function [`initialize(model, opt)`](https://github.com/YuxiXie/SG-Deep-Question-Generation/blob/9387c446499ca23e072c4d6a47865ae6d2ce1848/src/onqg/utils/model_builder.py#L58) for model parameter initilization.

**Comment by Frankszc** [comment]
Yeah, I have got it.
Thank you very much!!!!

**Comment by qjncxj** [comment]
In your python command line: "

-  python merge.py **data.json** dp.json crf_rsltn.json merged_data.json

where  I cannot find the file "data.json", but according to the context "Merge data file (train or valid) with the result files from Coreference Resolution and Dependency Parsing", I guess that  the "data.json" should be replaced by "data.train.json" or "data.valid.json", right?
