### ISSUE TITLE
Evaluation script!

### ISSUE THREAD

**Issue by yokee06** [YuxiXie/SG-Deep-Question-Generation#3]
Hello! 

Could you please provide the evaluation script?

Regards,
Yokesh

**Comment by YuxiXie** [comment]
Hi @yokee06 ! Thanks for asking.
We have just uploaded our evaluation code, [`evaluate_metrics.py`](https://github.com/YuxiXie/SG-Deep-Question-Generation/blob/master/evaluate_metrics.py), where we use the [Evaluation codes for MS COCO caption generation](https://github.com/salaniz/pycocoevalcap) for evaluation.
Kindly install pycocoevalcap and the pycocotools dependency, then you can run the evaluation code following the instrutions here: https://github.com/YuxiXie/SG-Deep-Question-Generation/blob/master/README.md#evaluating

**Comment by yokee06** [comment]
Thank you!
