### ISSUE TITLE
Prediction on the custom input

### ISSUE THREAD

**Issue by Shravankkk** [YuxiXie/SG-Deep-Question-Generation#6]
Hello,
Can anyone suggest the procedure to be followed to get the prediction on the input provided by us using the same trained model. We want to use our paragraph as input.
Regards,
Shravan

**Comment by raaedahmed23** [comment]
Hi, did you figure out how to do this?

**Comment by YuxiXie** [comment]
Hi, you may utilize the codes in `translate.py`, and disable the bleu calculation line in `Translator.py` if there is no ground-truth provided.
