### ISSUE TITLE
Question decoder

### ISSUE THREAD

**Issue by li-grass** [YuxiXie/SG-Deep-Question-Generation#7]
Hello!
I found when you evaluate the model in the validData, the input of the decoder still includes the question (i.e., the label) if I'm not wrong. I wanna know whether we can input the question of validData (label) in this situation.
Looking forward to your reply, thanks!

**Comment by YuxiXie** [comment]
Hi! Thanks for asking.
You could refer to the file [`src/onqg/utils/translate/Translator.py`](https://github.com/YuxiXie/SG-Deep-Question-Generation/blob/master/src/onqg/utils/translate/Translator.py) for validation. Here at [Line 130](https://github.com/YuxiXie/SG-Deep-Question-Generation/blob/master/src/onqg/utils/translate/Translator.py#L130) we update the decoded question through beam searching. So in fact we send the generated question back to the decoder (not the ground-truth label) during evaluation.
