### ISSUE TITLE
Answer incorporation

### ISSUE THREAD

**Issue by Arvindkrishna1997** [YuxiXie/SG-Deep-Question-Generation#8]
Hi! Thanks for the implementation. I couldn't find in the code where the answer embeddings are averaged and initialized as hidden layer for decoder as mentioned in the paper. I checked the Models.py, Encoders.py and Decoders.py. Also, how are you selecting the answer node out of all the nodes tagged with "ans" attribute as 1?

**Comment by YuxiXie** [comment]
Thanks for asking.
You can check the codes in [`Decoder.py`](https://github.com/YuxiXie/SG-Deep-Question-Generation/blob/903741522f8a6aff831e50baff070a87d0940ba9/src/onqg/models/Decoders.py#L114) for reference, we actually used sum in this version.
For the "ans" tags, you can check [`answer_tag.py`](https://github.com/YuxiXie/SG-Deep-Question-Generation/blob/master/build-semantic-graphs/answer_tag.py) for details. It generally depends on the word overlap between nodes and answers.
